sudo: required

language: java

services:
  - docker

jdk:
  - openjdk9

addons:
  sonarcloud:
    # Set this to match your repo - see this doc on how to set details https://docs.travis-ci.com/user/sonarcloud/
    organization: utplsql
    token: ${SONAR_TOKEN}

env:
  global:
    # Docker variables:
    - DOCKHER_HUB_REPO="${DOCKER_USER}/oracledb"
    - ORACLE_VERSION=11g-r2-xe
    - CONNECTION_STR='127.0.0.1:1521/XE'
    - DOCKER_OPTIONS='--shm-size=1g'

    # Adding utPLSQL-cli to path - to be able to invoke "utplsql" from command line
    - PATH=$PATH:${TRAVIS_BUILD_DIR}/utPLSQL-cli/bin
    # Adding Oracle SQLCL to path - to be able to invoke "sql" from command line
    - PATH=$PATH:${TRAVIS_BUILD_DIR}/sqlcl/bin

    # Project-specific database variables
    # used for creating the user in database, deploying source code and tests as well as executing the tests
    - DB_USER=ut3_demo
    - DB_PASS=ut3_demo
    #utPLSQL variables
    - UTPLSQL_DIR="utPLSQL"
    - CACHE_DIR=$HOME/.cache
    # Additionally, you need to set following variables as Travis secrets:
    #    DOCKER_USER
    #    DOCKER_PASSWORD
    #    ORACLE_OTN_USER
    #    ORACLE_OTN_PASSWORD
    #    DB_SYS_PASSWORD  - SYS account password for DB
  matrix:
    - UTPLSQL_VERSION='develop'
    - UTPLSQL_VERSION='v3.0.0' VERSION_PLACEHOLDER='utPLSQL - Version X.X.X.X'
    - UTPLSQL_VERSION='v3.0.4' VERSION_PLACEHOLDER='X.X.X.X'
    - UTPLSQL_VERSION='v3.1.1'

cache:
  pip: true
  directories:
    - $CACHE_DIR
    - node_modules

before_install:
  # Download Oracle sqlcl
  - .travis/install_sqlcl.sh -u ${ORACLE_OTN_USER} -p ${ORACLE_OTN_PASSWORD} -d ${CACHE_DIR} -o ${TRAVIS_BUILD_DIR}
  # Check if Oracle sqlcl it is installed correctly
  - sql -v

  # download and unzip utPLSQL-cli release
  - curl -Lk -o utPLSQL-cli.zip "https://github.com/utPLSQL/utPLSQL-cli/releases/download/v3.1.8/utPLSQL-cli.zip"
  - unzip utPLSQL-cli.zip && chmod -R u+x utPLSQL-cli

  # Download specified version of utPLSQL from utPLSQL github repo
  # Allows any utPLSQL branch/tag name to be used
  - git clone --depth=1 --branch=${UTPLSQL_VERSION} https://github.com/utPLSQL/utPLSQL.git ${UTPLSQL_DIR}

  # update version placeholder before install
  # This is only needed when downloading utPLSQL versions older than 3.1
  - if [[ -n ${VERSION_PLACEHOLDER} ]] ; then sed -i "s/${VERSION_PLACEHOLDER}/${UTPLSQL_VERSION}/g" ${UTPLSQL_DIR}/source/core/ut_utils.pks; fi

  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
  # download Oracle Database docker image from private repo and start the DB
  - time docker pull ${DOCKHER_HUB_REPO}:${ORACLE_VERSION}
  # start the docker container (DB)
  - docker run -d --name ${ORACLE_VERSION} ${DOCKER_OPTIONS} -p 1521:1521 ${DOCKHER_HUB_REPO}:${ORACLE_VERSION}
  # Wait for DB startup
  - time docker logs -f ${ORACLE_VERSION} | grep -m 1 "DATABASE IS READY TO USE!" --line-buffered

  # Install utPLSQL into the Database
  - .travis/install_utplsql.sh

install:
  # Create the demo project DB user account
  - source/setup_db_account.sh
  # Install project sources and tests
  - source/install.sh
  - test/install.sh

script:
  # Run tests
  - test/run.sh
  # Run sonar scanner and publish to sonar
  - sonar-scanner
